package softpos.gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.Rectangle;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import utilities.MySQLConnect;

public class InputPayment extends javax.swing.JDialog {
    DefaultTableModel model2;
    static SimpleDateFormat Datefmtshow = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    SimpleDateFormat DateTimeFmt = new SimpleDateFormat("dd/MM/yyyy (HH:mm)", Locale.ENGLISH);
    SimpleDateFormat SqlDateFmt = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
    SimpleDateFormat DateFmt = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    SimpleDateFormat TimeFmt = new SimpleDateFormat("HH:mm", Locale.ENGLISH);
    SimpleDateFormat FileDateFmt = new SimpleDateFormat("yyyyMMdd", Locale.ENGLISH) ;
    SimpleDateFormat FullTimeFmt = new SimpleDateFormat("HH:mm:ss", Locale.ENGLISH);
    SimpleDateFormat ShortTimeFmt = new SimpleDateFormat("HH:mm", Locale.ENGLISH);
    Date TempDate = new Date() ;
    
    String Branch_Name;
    String Branch_Code;
    String Branch_Type;

    /** Creates new form InputPayment */
    
    public InputPayment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Font myfont = new Font("Norasi", Font.PLAIN, 14);
        UIManager.put("Label.font", myfont);
        UIManager.put("Button.font", myfont);
        model2 = (DefaultTableModel) ShowTableLogin.getModel();
        ShowTableLogin.setShowGrid(true);
        ShowTableLogin.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        ShowTableLogin.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ShowTableLogin.setRowSelectionAllowed(true);
        ShowTableLogin.setShowGrid(true);
        ShowTableLogin.setShowHorizontalLines(true) ;
        ShowTableLogin.setShowVerticalLines(true) ;
        ShowTableLogin.setGridColor(Color.black);

        JTableHeader header = ShowTableLogin.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 16));

        int[] ColSize = {50, 300, 100, 100, 100 };
        for (int i = 0; i < 5; i++) {
            //int vColIndex = 0;
            TableColumn col = ShowTableLogin.getColumnModel().getColumn(i);
            col.setPreferredWidth(ColSize[i]);
        }
        
        DecimalFormat DoubleFmt = new DecimalFormat("##,###,##0.00");
        DecimalFormat IntegerFmt = new DecimalFormat("##,###,##0");
        DecimalFormat PersentFmt = new DecimalFormat("#,##0.00%");

        TableColumnModel tcm = ShowTableLogin.getColumnModel();

        TableTestFormatRenderer r = new TableTestFormatRenderer(IntegerFmt);

        r = new TableTestFormatRenderer(DoubleFmt);
        r.setHorizontalAlignment(SwingConstants.RIGHT);
        tcm.getColumn(2).setCellRenderer(r);

        r = new TableTestFormatRenderer(DoubleFmt);
        r.setHorizontalAlignment(SwingConstants.RIGHT);
        tcm.getColumn(3).setCellRenderer(r);
        
        r = new TableTestFormatRenderer(DoubleFmt);
        r.setHorizontalAlignment(SwingConstants.RIGHT);
        tcm.getColumn(4).setCellRenderer(r);
        String XDate = PublicVar.TempDate ;
        try {
            TempDate = DateFmt.parse(XDate);
        } catch (ParseException ex) {
            Logger.getLogger(InputPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        LoadDataFromFile() ;
        LoadDataToGrid() ;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     public void LoadDataFromFile() {
        try {
            Statement stmt = (Statement) MySQLConnect.con.createStatement();
            String SqlQuery = "select *from branch";
            ResultSet rec = stmt.executeQuery(SqlQuery);
            rec.first();
            if (rec.getRow() != 0) {
                Branch_Code = rec.getString("code");
                Branch_Name = rec.getString("name");
                Branch_Type = rec.getString("btype");
            }
            rec.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
     public void LoadDataToGrid() {
        try {
            Statement stmt = (Statement) MySQLConnect.con.createStatement();
            String LoadTableFile = "select *from rjfile where tdate ='" + SqlDateFmt.format(TempDate) + "' order by rjno";
            ResultSet rec = stmt.executeQuery(LoadTableFile);
            Date dt = new Date();
            int RowCount = model2.getRowCount();
            for (int i = 0; i <= RowCount - 1; i++) {
                model2.removeRow(0);
            }
            rec.first();
            if (rec.getRow() == 0) {
            } else {
                do {
                    if (rec.getString("rjno").equals("60") | rec.getString("rjno").equals("61") | rec.getString("rjno").equals("62") 
                            |rec.getString("rjno").equals("64")|rec.getString("rjno").equals("66")|rec.getString("rjno").equals("67")|rec.getString("rjno").equals("68")
                            |rec.getString("rjno").equals("70")|rec.getString("rjno").equals("71")|rec.getString("rjno").equals("72")
                            |rec.getString("rjno").equals("73")|rec.getString("rjno").equals("67")
                            | rec.getString("rjno").equals("T0") | rec.getString("rjno").equals("T1") | rec.getString("rjno").equals("T2") | rec.getString("rjno").equals("T3") | rec.getString("rjno").equals("T4") | rec.getString("rjno").equals("T5") | rec.getString("rjno").equals("T6") | rec.getString("rjno").equals("T7")|rec.getString("rjno").equals("T8")|rec.getString("rjno").equals("T9")) {
                        Object[] input = {
                            rec.getString("rjno"),
                            rec.getString("descname"),
                            rec.getDouble("mac1"),
                            rec.getDouble("mac2"),
                            rec.getDouble("mac3")
                        };
                        if (rec.getString("rjno").equals("60")) {
                            txtfixcode.setText(rec.getString("fixcode"));
                        }
                        model2.addRow(input);
                    }
                } while (rec.next());
                RowCount = model2.getRowCount();
                showCell(0, 0);
            }
            rec.close();
            stmt.close();
        } catch (SQLException e) {
            PUtility.ShowError(e.getMessage());
        }
    }
    public void showCell(int row, int column) {
        Rectangle rect = ShowTableLogin.getCellRect(row, column, true);
        ShowTableLogin.scrollRectToVisible(rect);
        ShowTableLogin.clearSelection();
        ShowTableLogin.setRowSelectionInterval(row, row);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ShowTableLogin = new javax.swing.JTable();
        bntOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtfixcode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ShowTableLogin.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        ShowTableLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RJNO", "รายการ (Description)", "เครื่อง 1", "เครื่อง 2", "เครื่อง 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ShowTableLogin.setOpaque(false);
        ShowTableLogin.setRowHeight(25);
        ShowTableLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ShowTableLoginKeyPressed(evt);
            }
        });
        ShowTableLogin.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                ShowTableLoginVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(ShowTableLogin);

        bntOK.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        bntOK.setText("ตกลง (OK)");
        bntOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bntOKMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jLabel3.setText("ใส่รหัสธนาคาร (Bank Code PAY In 1)");

        txtfixcode.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfixcode, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(bntOK, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntOK, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtfixcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(705, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void ShowTableLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ShowTableLoginKeyPressed

}//GEN-LAST:event_ShowTableLoginKeyPressed

private void ShowTableLoginVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_ShowTableLoginVetoableChange

}//GEN-LAST:event_ShowTableLoginVetoableChange

private void bntOKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntOKMouseReleased
    bntOKClick() ;
}//GEN-LAST:event_bntOKMouseReleased
public void bntOKClick() {
    UpdateToDataBase() ;
    ProcessSum() ;
    ClearRjFile() ;
    SaveDataToRJFile() ;
    this.dispose();
}
public void ClearRjFile() {
    try {
            Statement stmt = (Statement) MySQLConnect.con.createStatement();
            String SQLQuery = "delete from rjfile where tdate='"+SqlDateFmt.format(TempDate)+"'";
            stmt.executeUpdate(SQLQuery);
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }    
}
public void SaveDataToRJFile() {
    try {
            Statement stmt = (Statement) MySQLConnect.con.createStatement();
            String SQLQuery = "select *from surrj ";
            ResultSet rec = stmt.executeQuery(SQLQuery);
            rec.first();
            if (rec.getRow() == 0) {
            } else {
                do {
                    Statement stmt2 = (Statement) MySQLConnect.con.createStatement();
                    String InsertQuery = "insert into rjfile (brcode,tdate,rjno,dept,account,sub,descname," +
                            "fixcode,mac1,mac2,mac3,total,nettotal,vat) " +
                            "values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement prm = (PreparedStatement) MySQLConnect.con.prepareStatement(InsertQuery);
                    prm.setString(1, Branch_Code);
                    prm.setString(2, SqlDateFmt.format(TempDate));
                    prm.setString(3, rec.getString("rjno"));
                    prm.setString(4, rec.getString("dept"));
                    prm.setString(5, rec.getString("account"));
                    prm.setString(6, rec.getString("sub"));
                    prm.setString(7, rec.getString("tdesc"));
                    prm.setString(8, rec.getString("fixcode"));
                    prm.setDouble(9, rec.getDouble("mac1"));
                    prm.setDouble(10, rec.getDouble("mac2"));
                    prm.setDouble(11, rec.getDouble("mac3"));
                    prm.setDouble(12, rec.getDouble("mac1")+rec.getDouble("mac2")+rec.getDouble("mac3"));
                    prm.setDouble(13, 0);
                    prm.setDouble(14, 0);
                    prm.executeUpdate();
                    stmt2.close();
                } while (rec.next());
            }
            rec.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }    
}
public void ProcessSum() {
    try {
            Statement stmt = (Statement) MySQLConnect.con.createStatement();
            String LoadTableFile ="select *from surrj";
            ResultSet rec = stmt.executeQuery(LoadTableFile);
            rec.first();
            if (rec.getRow() == 0) {
            } else {
                do {
                    String TRJNo = rec.getString("rjno") ;
                    String TDept = rec.getString("dept") ;
                    String TProcess = rec.getString("process") ;
                    if (!TProcess.equals("")) {
                       if (TProcess.substring(0,3).equals("SUM")) {
                           ProcessSumRJ(TRJNo,TProcess) ;
                       }
                    }
                } while (rec.next());
            }
            rec.close();
            stmt.close();
        } catch (SQLException e) {
            PUtility.ShowError(e.getMessage());
        }
}
public void ProcessSumRJ(String TRJNo,String TProcess) {
        Double XSum1 = 0.0 ;
        Double XSum2 = 0.0 ;
        Double XSum3 = 0.0 ;
        String XRJNo = "" ;
        try {
            Statement stmt = (Statement) MySQLConnect.con.createStatement();
            String SQLQuery = "select *from surrj";
            ResultSet rec = stmt.executeQuery(SQLQuery);
            rec.first();
            if (rec.getRow() == 0) {
            } else {
                do {
                    XRJNo = rec.getString("rjno") ;
                    int XPoint = TProcess.indexOf(XRJNo) ;
                    if (XPoint>0) {
                       String XSign = TProcess.substring(XPoint-1,XPoint) ;
                       if (XSign.equals("-")) {
                           XSum1 = XSum1-rec.getDouble("mac1") ;
                           XSum2 = XSum2-rec.getDouble("mac2") ;
                           XSum3 = XSum3-rec.getDouble("mac3") ;
                       } else {
                           XSum1 = XSum1+rec.getDouble("mac1") ;
                           XSum2 = XSum2+rec.getDouble("mac2") ;
                           XSum3 = XSum3+rec.getDouble("mac3") ;
                       }
                    }
                } while (rec.next());
            }
            UpdateSurRj(TRJNo, XSum1, XSum2, XSum3);
            rec.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
         
        
    } 
 public void UpdateSurRj(String TRjNo, Double TAmt1, Double TAmt2, Double TAmt3) {
        try {
            Statement stmt = (Statement) MySQLConnect.con.createStatement();
            String InsertQuery = "update surrj set mac1=?,mac2=?,mac3=? where rjno=? " ;
            PreparedStatement prm = (PreparedStatement) MySQLConnect.con.prepareStatement(InsertQuery);
            prm.setDouble(1, TAmt1);
            prm.setDouble(2, TAmt2);
            prm.setDouble(3, TAmt3);
            prm.setString(4, TRjNo);
            prm.executeUpdate();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void UpdateToDataBase() {
        int maxrow;
        String RJNo = "";
        String fixcode = "" ;
        Double Mac1 = 0.0;
        Double Mac2 = 0.0;
        Double Mac3 = 0.0;
        Double Total = 0.0 ;
        maxrow = ShowTableLogin.getRowCount();
        if (maxrow > 0) {
            for (int i = 0; i < maxrow; i++) {
                RJNo = ShowTableLogin.getValueAt(i, 0).toString();
                Mac1 = (Double) ShowTableLogin.getValueAt(i, 2);
                Mac2 = (Double) ShowTableLogin.getValueAt(i, 3);
                Mac3 = (Double) ShowTableLogin.getValueAt(i, 4);
                Total = Mac1+Mac2+Mac3 ;
                if (RJNo.equals("60")) {
                    fixcode = txtfixcode.getText() ;
                } else {
                    fixcode = "" ;
                }
                try {
                    Statement stmt = (Statement) MySQLConnect.con.createStatement();
                    String LoadTableFile = "update surrj set mac1=" + Mac1 + ",mac2=" + Mac2 + ",mac3=" + Mac3 +",gosstotal="+Total+",fixcode='"+fixcode+"' where rjno='" + RJNo + "'";
                    stmt.executeUpdate(LoadTableFile);
                    stmt.close();
                } catch (SQLException e) {
                    PUtility.ShowError(e.getMessage());
                }

            }
        } else {
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InputPayment dialog = new InputPayment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ShowTableLogin;
    private javax.swing.JButton bntOK;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtfixcode;
    // End of variables declaration//GEN-END:variables
     public class TableTestFormatRenderer extends DefaultTableCellRenderer {

        private Format formatter;

        public TableTestFormatRenderer(Format formatter) {
            if (formatter == null) {
                throw new NullPointerException();
            }
            this.formatter = formatter;
        }

        protected void setValue(Object obj) {
            setText(obj == null ? "" : formatter.format(obj));
        }
    }
}
