package softpos.gui;

import Controller.CreditCard_Controller;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import utilities.MySQLConnect;

public class jdi_CreditCardSetup extends javax.swing.JDialog {

    /** Creates new form jdi_branch */
    DecimalFormat doubleFmt = new DecimalFormat("##,###,##0.00");
    SimpleDateFormat dateFmt1 = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
    DefaultTableModel model;

    public jdi_CreditCardSetup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        setTalble();

        txt1.requestFocus();
        btn_remove.setEnabled(false);
        loadCreditFile();
    }

    private void setTalble() {
        model = (DefaultTableModel) tblCredit.getModel();
        tblCredit.setShowGrid(true);
        tblCredit.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblCredit.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblCredit.setRowSelectionAllowed(true);
        tblCredit.setBackground(java.awt.Color.WHITE);
        tblCredit.setGridColor(Color.gray);

        JTableHeader header = tblCredit.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 16));
        tblCredit.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 14));
        tblCredit.setRowHeight(25);
        int cl = model.getColumnCount();
        int[] colsize = {80, 100, 200, 80, 80, 120};
        for (int c = 0; c < cl; c++) {
            tblCredit.getColumnModel().getColumn(c).setPreferredWidth(colsize[c]);
        }
        TableColumnModel tcm = tblCredit.getColumnModel();
        DefaultTableCellRenderer d;

        d = new DefaultTableCellRenderer();
        d.setHorizontalAlignment(SwingConstants.LEADING);
        tcm.getColumn(0).setCellRenderer(d);
        tcm.getColumn(1).setCellRenderer(d);
        tcm.getColumn(2).setCellRenderer(d);
        d = new DefaultTableCellRenderer();
        d.setHorizontalAlignment(SwingConstants.CENTER);

        tcm.getColumn(3).setCellRenderer(d);
        tcm.getColumn(4).setCellRenderer(d);
        tcm.getColumn(5).setCellRenderer(d);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupCre = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_addNew = new javax.swing.JButton();
        btn_cancle = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt4 = new javax.swing.JFormattedTextField();
        txt5 = new javax.swing.JFormattedTextField();
        txt3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCredit = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRowCount = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        menu_Add1 = new javax.swing.JMenuItem();
        menu_Cancle1 = new javax.swing.JMenuItem();
        menu_Save1 = new javax.swing.JMenuItem();
        menu_Remove2 = new javax.swing.JMenuItem();
        menu_exit1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("กำหนดข้อมูลรายละเอียดสินค้า/บริการ (Product&Service Setting)"); // NOI18N
        setBackground(new java.awt.Color(236, 236, 236));
        setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setInheritsPopupMenu(true);

        btn_addNew.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_addNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.gif"))); // NOI18N
        btn_addNew.setText("เพิ่มเอกสาร"); // NOI18N
        btn_addNew.setToolTipText("เพิ่มเอกสาร"); // NOI18N
        btn_addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addNewActionPerformed(evt);
            }
        });

        btn_cancle.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_cancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancle.gif"))); // NOI18N
        btn_cancle.setText("ยกเลิก"); // NOI18N
        btn_cancle.setToolTipText("ยกเลิก"); // NOI18N
        btn_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancleActionPerformed(evt);
            }
        });

        btn_remove.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.gif"))); // NOI18N
        btn_remove.setText("ลบข้อมูล"); // NOI18N
        btn_remove.setToolTipText("ลบข้อมูล"); // NOI18N
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.gif"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.gif"))); // NOI18N
        btn_save.setText("บันทึกข้อมูล"); // NOI18N
        btn_save.setToolTipText("บันทึกข้อมูล"); // NOI18N
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_addNew)
                .addGap(0, 0, 0)
                .addComponent(btn_cancle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_remove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_exit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_addNew, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(btn_cancle, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_remove, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel1.setText("รหัสบัตรเครดิต (Cr-Code)"); // NOI18N

        txt1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt1FocusLost(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt1KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel2.setText("ชื่อบัตรเครดิต (Card Name)"); // NOI18N

        txt2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txt2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt2FocusGained(evt);
            }
        });
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt2KeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel3.setText("รหัสธนาคารเจ้าของบัคร (Bank)"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel4.setText("กำหนดให้รับหมายเลขบัตรด้วยหรือไม่ ?"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel5.setText("จำนวน % Charge เมื่อรับชำระด้วยบัตรเครดิตนี้"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel6.setText("จำนวน % หักส่วนลดเมื่อรับชำระด้วยบัตรเครดิตนี้"); // NOI18N

        txt4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txt4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt4.setText("0.00");
        txt4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt4KeyReleased(evt);
            }
        });

        txt5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txt5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt5.setText("0.00");
        txt5.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt5KeyReleased(evt);
            }
        });

        txt3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        txt3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt3FocusGained(evt);
            }
        });
        txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt3KeyReleased(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null)));

        groupCre.add(yes);
        yes.setSelected(true);
        yes.setText("Yes");
        yes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yesKeyPressed(evt);
            }
        });

        groupCre.add(no);
        no.setText("No");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(yes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(no)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(yes)
                .addComponent(no))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt4)
                            .addComponent(txt5))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(176, 214, 217));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("กำหนดรายการบัตรเครดิต (Credit Card)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCredit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ธนาคาร", "รหัสบัคร", "ชื่อบัคร/รายการ", "หักส่วนลด", "Charge", "ใส่หมายเลขบัคร"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCredit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCreditMouseClicked(evt);
            }
        });
        tblCredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCreditKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCredit);

        jLabel12.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel12.setText("จำนวนรายการบัตร");

        jLabel13.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrow.gif"))); // NOI18N

        txtRowCount.setEditable(false);
        txtRowCount.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        txtRowCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRowCount.setText("txt15");
        txtRowCount.setFocusable(false);
        txtRowCount.setRequestFocusEnabled(false);

        jMenu4.setText("ฟังก์ชัน (Function)"); // NOI18N
        jMenu4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N

        menu_Add1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menu_Add1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Add1.setText("เพิ่มข้อมูลใหม่ (Add New)"); // NOI18N
        menu_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_AddActionPerformed(evt);
            }
        });
        jMenu4.add(menu_Add1);

        menu_Cancle1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Cancle1.setText("ยกเลิกการแก้ไข (Cancle All)"); // NOI18N
        menu_Cancle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CancleActionPerformed(evt);
            }
        });
        jMenu4.add(menu_Cancle1);

        menu_Save1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_Save1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Save1.setText("บันทึกข้อมูล (Save/Update)"); // NOI18N
        menu_Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_SaveActionPerformed(evt);
            }
        });
        jMenu4.add(menu_Save1);

        menu_Remove2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menu_Remove2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Remove2.setText("ลบข้อมูล (Remove)"); // NOI18N
        menu_Remove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_RemoveActionPerformed(evt);
            }
        });
        jMenu4.add(menu_Remove2);

        menu_exit1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menu_exit1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_exit1.setText("ออกจากการทำงาน (Exit)"); // NOI18N
        menu_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exitActionPerformed(evt);
            }
        });
        jMenu4.add(menu_exit1);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(10, 10, 10)
                                .addComponent(txtRowCount, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtRowCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(59, 59, 59))
        );

        getAccessibleContext().setAccessibleName("กำหนดรายการบัตรเครดิต (Credit Card Setup)");

        setSize(new java.awt.Dimension(1024, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btn_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancleActionPerformed
    clearForm();
}//GEN-LAST:event_btn_cancleActionPerformed

private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_btn_exitActionPerformed

private void btn_addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addNewActionPerformed
    clearForm();
}//GEN-LAST:event_btn_addNewActionPerformed


//    public boolean validateForm() {
//        
//    }
private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
            CreditCard_Controller ctrl = new CreditCard_Controller();//GEN-LAST:event_btn_removeActionPerformed
            if (ctrl.seekCredit(txt1.getText().trim())) {
                int confirm = JOptionPane.showConfirmDialog(this, "คุณต้องการลบข้อมูลบัตรเครดิต " + txt1.getText() + " หรือไม่", "Cofirm Remove", JOptionPane.OK_CANCEL_OPTION);
                if (confirm == JOptionPane.OK_OPTION) {
                    if (ctrl.removeCredit(txt1.getText())) {
                        JOptionPane.showMessageDialog(this, "ลบข้อมูลบัตร " + txt1.getText() + " แล้ว", "Information", JOptionPane.INFORMATION_MESSAGE);
                        loadCreditFile();
                        clearForm();
                    } else {
                        JOptionPane.showMessageDialog(this, "เกิดความผิดพลาดไม่สามารถลบข้อมูลบัตรได้", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
}                                          

private void menu_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_AddActionPerformed
    clearForm();
}//GEN-LAST:event_menu_AddActionPerformed

private void menu_CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CancleActionPerformed
    clearForm();
}//GEN-LAST:event_menu_CancleActionPerformed

private void menu_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_SaveActionPerformed
    btn_saveActionPerformed(null);
}//GEN-LAST:event_menu_SaveActionPerformed

private void menu_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_RemoveActionPerformed
// TODO add your handling code here:
    btn_removeActionPerformed(evt);
}//GEN-LAST:event_menu_RemoveActionPerformed

private void menu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exitActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_menu_exitActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    txt1.requestFocus();
}//GEN-LAST:event_formWindowOpened

private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
// TODO add your handling code here:
    //int confirm = JOptionPane.showConfirmDialog(this,"คุณต้องการออกจากโปรแกรมหรือไม่","MyCps",JOptionPane.QUESTION_MESSAGE);
    //if(confirm == JOptionPane.OK_OPTION){
    dispose();
//}
}//GEN-LAST:event_btn_exitMouseClicked

private void menu_Remove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Remove1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_menu_Remove1ActionPerformed

private void tblCreditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCreditMouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() == 2) {
        tblCreditAction(tblCredit.getSelectedRow());
    }


}//GEN-LAST:event_tblCreditMouseClicked

private void tblCreditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCreditKeyPressed
// TODO add your handling code here:
    int row = tblCredit.getSelectedRow();
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        tblCreditAction(tblCredit.getSelectedRow());

    }
}//GEN-LAST:event_tblCreditKeyPressed

private void txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyReleased
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        cmdCheckCredit();
    }

}//GEN-LAST:event_txt1KeyReleased

private void txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyReleased
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        String value = txt2.getText().trim();
        if (value.length() > 0) {
            txt3.requestFocus();
        }
    }
}//GEN-LAST:event_txt2KeyReleased

private void txt3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt3KeyReleased
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        String value = txt3.getText().trim();
        if (value.length() > 0) {
            txt4.selectAll();
            txt4.requestFocus();
        }
    }
}//GEN-LAST:event_txt3KeyReleased

private void yesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yesKeyPressed
//if(evt.getKeyCode()==java.awt.event.KeyEvent.){
//    txt3.requestFocus();
//}
//else if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_KP_RIGHT){
//    no.requestFocus();
//}
}//GEN-LAST:event_yesKeyPressed

private void txt4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt4KeyReleased
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        String value = txt3.getText().trim();
        if (value.length() > 0) {
            txt5.selectAll();
            txt5.requestFocus();
        }
    }
}//GEN-LAST:event_txt4KeyReleased

private void txt5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyReleased
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        String value = txt3.getText().trim();
        if (value.length() > 0) {
            txt2.requestFocus();
        }
    }
}//GEN-LAST:event_txt5KeyReleased

private void txt2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt2FocusGained
    txt2.selectAll();
}//GEN-LAST:event_txt2FocusGained

private void txt3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt3FocusGained
    txt3.selectAll();
}//GEN-LAST:event_txt3FocusGained

private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
    if (validateForm()) {
        CreditCard_Controller ctrl = new CreditCard_Controller();
        String CrCode = txt1.getText().trim();
        String CrName = txt2.getText().trim();
        String CrBank = txt3.getText().trim();
        String CrCharge = txt4.getText().trim();
        String CrRedule = txt5.getText().trim();
        String CrGetCardNo = "";
        if (yes.isSelected()) {
            CrGetCardNo = "Y";
        } else {
            CrGetCardNo = "N";
        }
        if (ctrl.insertCredit(CrCode, CrBank, CrName, CrGetCardNo, CrCharge, CrRedule)) {
            JOptionPane.showMessageDialog(this, "บันทึกข้อมูลแล้ว", "Information", JOptionPane.INFORMATION_MESSAGE);
            loadCreditFile();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "เกิดความผิดพลาดไม่สามารถบันทึกข้อมูลได้", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}//GEN-LAST:event_btn_saveActionPerformed

private void txt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt1FocusLost
    cmdCheckCredit();
}//GEN-LAST:event_txt1FocusLost
    private void clearForm() {
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("0.00");
        txt4.setValue(0);
        txt5.setText("0.00");
        txt5.setValue(0);
        yes.setSelected(true);
        btn_remove.setEnabled(false);
        txt1.setBackground(Color.white);
        tblCredit.setRowSelectionInterval(0, 0);
        txt1.setEditable(true);
        txt1.requestFocus();
    }

    private void tblCreditAction(int row) {

        txt1.setText((String) model.getValueAt(row, 1));
        txt2.setText((String) model.getValueAt(row, 2));
        txt3.setText((String) model.getValueAt(row, 0));
        String charge = (String) model.getValueAt(row, 4);
        String redule = (String) model.getValueAt(row, 3);
        txt4.setText(charge);
        txt5.setText(redule);
        try {
            txt4.setValue(Float.parseFloat(charge));
            txt5.setValue(Float.parseFloat(redule));
        } catch (Exception e) {
        }
        String check = (String) model.getValueAt(row, 5);
        txt1.setBackground(new java.awt.Color(250, 217, 184));
        txt1.setEditable(false);
        if (check.equals("Y")) {
            yes.setSelected(true);
        } else {
            no.setSelected(true);
        }
        txt2.selectAll();
        txt2.requestFocus();
        btn_remove.setEnabled(true);
    }

    private boolean validateForm() {
        if (txt1.getText().trim().length() < 1) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุรหัสบัตรเครดิต");
            txt1.requestFocus();
            return false;
        } else if (txt2.getText().trim().length() < 1) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุชื่อบัตรเครดิต");
            txt2.requestFocus();
            return false;
        } else if (txt3.getText().trim().length() < 1) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุธนาคารเจ้าของบัตรเครดิต");
            txt3.requestFocus();
            return false;
        } else if (txt3.getText().trim().length() > 3) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุธนาคารเจ้าของบัตรเครดิต ไม่เกิน 3 ตัว");
            txt3.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private void cmdCheckCredit() {
        String value = txt1.getText().trim();
        boolean check = false;
        if (value.length() > 0) {
            String fnd = "";
            int cnt = model.getRowCount();
            end:
            for (int i = 0; i < cnt; i++) {
                start:
                fnd = (String) model.getValueAt(i, 1);
                if (fnd.equals(value)) {
                    tblCreditAction(i);
                    tblCredit.setRowSelectionInterval(0, i);
                    check = true;
                    break end;
                }
            }
            if (!check) {
                txt1.setBackground(new java.awt.Color(250, 217, 184));
                txt1.setEditable(false);
                txt2.requestFocus();
            }
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jdi_CreditCardSetup dialog = new jdi_CreditCardSetup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addNew;
    private javax.swing.JButton btn_cancle;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_save;
    private javax.swing.ButtonGroup groupCre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JMenuItem menu_Add1;
    private javax.swing.JMenuItem menu_Cancle1;
    private javax.swing.JMenuItem menu_Remove2;
    private javax.swing.JMenuItem menu_Save1;
    private javax.swing.JMenuItem menu_exit1;
    private javax.swing.JRadioButton no;
    private javax.swing.JTable tblCredit;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JFormattedTextField txt4;
    private javax.swing.JFormattedTextField txt5;
    private javax.swing.JTextField txtRowCount;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables

    private void loadCreditFile() {
        Statement stmt = null;
        ResultSet rs = null;
        String sql = "Select * From creditfile ";
        try {
            stmt = (Statement) MySQLConnect.con.createStatement();
            rs = stmt.executeQuery(sql);
            if (rs != null) {
                cleartblCredit();
            }
            while (rs.next()) {
                String[] data = new String[6];
                data[0] = rs.getString("CrBank");
                data[1] = rs.getString("CrCode");
                data[2] = rs.getString("CrName");
                data[3] = rs.getString("CrRedule");
                data[4] = rs.getString("CrCharge");
                data[5] = rs.getString("CrGetCardNo");
                model.addRow(data);
            }
            rs.close();
            stmt.close();
            txtRowCount.setText(model.getRowCount() + "");
            tblCredit.setRowSelectionInterval(0, 0);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void cleartblCredit() {
        int cnt = model.getRowCount();
        if (cnt > 0) {
            for (int q = 0; q < cnt; q++) {
                model.removeRow(0);
            }
        }
    }
}
