package softpos.gui;

import Controller.CuponBean;
import Controller.Cupon_Controller;
import java.awt.Frame;
import java.awt.Point;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import utilities.DateChooser.DateChooseDialog;

public class jdi_Special_Cupon_Setup extends javax.swing.JDialog {

    /** Creates new form jdi_branch */
    DecimalFormat doubleFmt = new DecimalFormat("##,###,##0.00");
    SimpleDateFormat dateFmtE = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
    SimpleDateFormat dateFmtT = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH);
    DefaultTableModel model;
    DefaultTableModel model2;
    private java.util.List listCupon = null;
    private boolean checkRemove = false;

    public jdi_Special_Cupon_Setup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        model = (DefaultTableModel) tblCupon.getModel();
        tblCupon.setShowGrid(true);
        tblCupon.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblCupon.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblCupon.setRowSelectionAllowed(true);
        tblCupon.setBackground(java.awt.Color.WHITE);
        tblCupon.setGridColor(java.awt.Color.gray);
        TableColumn column = null;
        int[] colSize = {60, 80,200, 100, 100, 300, 80, 100, 100, 100, 100};
        for (int i = 0; i < colSize.length; i++) {
            column = tblCupon.getColumnModel().getColumn(i);
            column.setPreferredWidth(colSize[i]);
        }

        TableColumnModel tcm = tblCupon.getColumnModel();
        DefaultTableCellRenderer d;

        d = new DefaultTableCellRenderer();
        d.setHorizontalAlignment(SwingConstants.LEADING);
        tcm.getColumn(0).setCellRenderer(d);
        tcm.getColumn(1).setCellRenderer(d);
        tcm.getColumn(2).setCellRenderer(d);
        tcm.getColumn(5).setCellRenderer(d);

        d = new DefaultTableCellRenderer();
        d.setHorizontalAlignment(SwingConstants.CENTER);
        tcm.getColumn(3).setCellRenderer(d);
        tcm.getColumn(4).setCellRenderer(d);
        tcm.getColumn(6).setCellRenderer(d);

        d = new DefaultTableCellRenderer();
        d.setHorizontalAlignment(SwingConstants.RIGHT);
        tcm.getColumn(7).setCellRenderer(d);
        tcm.getColumn(8).setCellRenderer(d);
        tcm.getColumn(9).setCellRenderer(d);
        tcm.getColumn(10).setCellRenderer(d);

        JTableHeader header = tblCupon.getTableHeader();
        header.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 14));
        tblCupon.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 14));
        tblCupon.setRowHeight(25);

        model2 = (DefaultTableModel) tblPLU.getModel();
        JTableHeader header2 = tblPLU.getTableHeader();
        header2.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 14));
        tblPLU.setFont(new java.awt.Font("Norasi", java.awt.Font.PLAIN, 14));
        tblPLU.setRowHeight(25);
        rd1.setSelected(true);
        loadDataToTblCupon();
        clearForm();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cupons = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_addNew = new javax.swing.JButton();
        btn_cancle = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        start = new javax.swing.JFormattedTextField();
        end = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_Date1 = new javax.swing.JButton();
        btn_Date2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        barcode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCupon = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        strDay = new javax.swing.JTextField();
        btn_Date = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        chMember = new javax.swing.JComboBox();
        strtype = new javax.swing.JTextField();
        btn_SaleType1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        te1 = new javax.swing.JCheckBox();
        tt1 = new javax.swing.JCheckBox();
        tw1 = new javax.swing.JCheckBox();
        tp1 = new javax.swing.JCheckBox();
        td1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        salemin = new javax.swing.JFormattedTextField();
        jPanel9 = new javax.swing.JPanel();
        rdDiscount = new javax.swing.JRadioButton();
        rdnDiscount = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        rdService = new javax.swing.JRadioButton();
        rdnService = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cuDisc = new javax.swing.JFormattedTextField();
        cuDiscBath = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rd1 = new javax.swing.JRadioButton();
        rd2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        plucode = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPLU = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        fixbranch2 = new javax.swing.JTextField();
        fixbranch1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        fixbranch3 = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        menu_Add1 = new javax.swing.JMenuItem();
        menu_Cancle1 = new javax.swing.JMenuItem();
        menu_Save1 = new javax.swing.JMenuItem();
        menu_Remove2 = new javax.swing.JMenuItem();
        menu_exit1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("กำหนดรายการบัตรคูปองพิเศษ (Special Coupon Setup)"); // NOI18N
        setBackground(new java.awt.Color(236, 236, 236));
        setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_addNew.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_addNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.gif"))); // NOI18N
        btn_addNew.setText("เพิ่มเอกสาร"); // NOI18N
        btn_addNew.setToolTipText("เพิ่มเอกสาร"); // NOI18N
        btn_addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addNewActionPerformed(evt);
            }
        });

        btn_cancle.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_cancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancle.gif"))); // NOI18N
        btn_cancle.setText("ยกเลิก"); // NOI18N
        btn_cancle.setToolTipText("ยกเลิก"); // NOI18N
        btn_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancleActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.gif"))); // NOI18N
        btn_save.setText("บันทึก"); // NOI18N
        btn_save.setToolTipText("บันทึกข้อมูล"); // NOI18N
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_remove.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        btn_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.gif"))); // NOI18N
        btn_remove.setText("ลบข้อมูล"); // NOI18N
        btn_remove.setToolTipText("ลบข้อมูล"); // NOI18N
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.gif"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(147, 202, 238));
        jTextField3.setFont(new java.awt.Font("Norasi", 0, 17)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("กำหนดรายการบัตรคูปองพิเศษ "); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(213, 36, 1), null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_addNew, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btn_cancle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_cancle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_addNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 230, 205));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel1.setText("รหัสคูปอง (Coupon Code)"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel2.setText("รายละเอียด / ชื่อบัตรคูปอง"); // NOI18N

        code.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeKeyReleased(evt);
            }
        });

        name.setEditable(false);
        name.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nameMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel3.setText("ช่วงวันที่ ที่สามารถให้ส่วนลดได้"); // NOI18N

        start.setEditable(false);
        start.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                startMouseReleased(evt);
            }
        });
        start.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                startKeyReleased(evt);
            }
        });

        end.setEditable(false);
        end.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        end.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                endMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel4.setText("ถึง"); // NOI18N

        btn_Date1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying glass.jpg"))); // NOI18N
        btn_Date1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Date1MouseClicked(evt);
            }
        });
        btn_Date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Date1ActionPerformed(evt);
            }
        });

        btn_Date2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying glass.jpg"))); // NOI18N
        btn_Date2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Date2MouseClicked(evt);
            }
        });
        btn_Date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Date2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel10.setText("Barcode"); // NOI18N

        barcode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barcodeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btn_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btn_Date2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(btn_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Date2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCupon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblCupon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cucode", "Barcode", "CuName", "CuBegin", "CuEnd", "CuStrDay", "CuType", "CuAdisc", "CuADiscBath", "CuBDisc", "CuADiscBath"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCupon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCuponMouseClicked(evt);
            }
        });
        tblCupon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCuponKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCupon);

        jPanel3.setBackground(new java.awt.Color(255, 230, 205));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel5.setText("ใช้ได้เฉพาะวัน (Day)"); // NOI18N

        strDay.setEditable(false);
        strDay.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N

        btn_Date.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.gif"))); // NOI18N
        btn_Date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DateMouseClicked(evt);
            }
        });
        btn_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DateActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(175, 91, 254));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(244, 244, 244));
        c1.setText("วันอาทิตย์");
        c1.setEnabled(false);
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        c2.setForeground(new java.awt.Color(244, 244, 244));
        c2.setText("วันจันทร์");
        c2.setEnabled(false);

        c3.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        c3.setForeground(new java.awt.Color(244, 244, 244));
        c3.setText("วันอังคาร");
        c3.setEnabled(false);

        c4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        c4.setForeground(new java.awt.Color(244, 244, 244));
        c4.setText("วันพุธ");
        c4.setEnabled(false);

        c5.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        c5.setForeground(new java.awt.Color(244, 244, 244));
        c5.setText("วันพฤหัสฯ");
        c5.setEnabled(false);

        c6.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        c6.setForeground(new java.awt.Color(244, 244, 244));
        c6.setText("วันศุกร์");
        c6.setEnabled(false);

        c7.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        c7.setForeground(new java.awt.Color(244, 244, 244));
        c7.setText("วันเสาร์");
        c7.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(c1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(c6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(c5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(c4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(c3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(c2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(c1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel7.setText("ใช้เป็นส่วนลดหลัก"); // NOI18N

        chMember.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Y", "N" }));
        chMember.setEnabled(false);

        strtype.setEditable(false);

        btn_SaleType1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.gif"))); // NOI18N
        btn_SaleType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaleType1ActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(175, 91, 254));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        te1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        te1.setForeground(new java.awt.Color(244, 244, 244));
        te1.setText("Eat-In");
        te1.setEnabled(false);
        te1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                te1ActionPerformed(evt);
            }
        });

        tt1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tt1.setForeground(new java.awt.Color(244, 244, 244));
        tt1.setText("Tale Away");
        tt1.setEnabled(false);
        tt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tt1ActionPerformed(evt);
            }
        });

        tw1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tw1.setForeground(new java.awt.Color(244, 244, 244));
        tw1.setText("Whole Sale");
        tw1.setEnabled(false);
        tw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tw1ActionPerformed(evt);
            }
        });

        tp1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tp1.setForeground(new java.awt.Color(244, 244, 244));
        tp1.setText("Pinto");
        tp1.setEnabled(false);
        tp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp1ActionPerformed(evt);
            }
        });

        td1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        td1.setForeground(new java.awt.Color(244, 244, 244));
        td1.setText("Delivery");
        td1.setEnabled(false);
        td1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                td1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(te1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tt1)
                .addGap(6, 6, 6)
                .addComponent(td1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tw1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tw1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(tt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(te1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(td1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Norasi", 1, 14)); // NOI18N
        jLabel11.setText("Sale Type"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel12.setText("ยอดซื้อขั้นต่ำที่ให้ส่วนลดได้"); // NOI18N

        salemin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        salemin.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(rdDiscount);
        rdDiscount.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        rdDiscount.setText("Redule ส่วนลดได้");

        buttonGroup1.add(rdnDiscount);
        rdnDiscount.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        rdnDiscount.setText("Redule ส่วนลดไม่ได้");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(rdDiscount)
                .addGap(18, 18, 18)
                .addComponent(rdnDiscount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdnDiscount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(rdDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup2.add(rdService);
        rdService.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        rdService.setText("ลด Service Charge");

        buttonGroup2.add(rdnService);
        rdnService.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        rdnService.setText("ไม่ลด Service Charge");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(rdService)
                .addGap(18, 18, 18)
                .addComponent(rdnService)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdnService, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(rdService, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(strDay, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(65, 65, 65)
                            .addComponent(strtype, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_SaleType1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chMember, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salemin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(strDay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_SaleType1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(strtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chMember, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salemin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 230, 205));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBackground(new java.awt.Color(175, 91, 254));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel6.setText("ส่วนลดเป็น %"); // NOI18N

        cuDisc.setEditable(false);
        cuDisc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cuDisc.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        cuDisc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuDiscMouseReleased(evt);
            }
        });

        cuDiscBath.setEditable(false);
        cuDiscBath.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cuDiscBath.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        cuDiscBath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cuDiscBathMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel8.setText("ส่วนลด (บาท)"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuDiscBath, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(cuDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cuDiscBath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cupons.add(rd1);
        rd1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        rd1.setText("ให้ส่วนลดได้เฉพาะรายการที่กำหนด");
        rd1.setEnabled(false);

        cupons.add(rd2);
        rd2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        rd2.setText("ให้ส่วนลดได้ทุกรายการที่ลดได้");
        rd2.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd1)
                    .addComponent(rd2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(rd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd2))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel9.setText("PLU Code"); // NOI18N

        plucode.setEditable(false);
        plucode.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        plucode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                plucodeKeyReleased(evt);
            }
        });

        tblPLU.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblPLU.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        tblPLU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLU Code", "ชื่อสินค้า (Description)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPLU.setRowHeight(20);
        jScrollPane2.setViewportView(tblPLU);
        if (tblPLU.getColumnModel().getColumnCount() > 0) {
            tblPLU.getColumnModel().getColumn(0).setResizable(false);
            tblPLU.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fixbranch2.setText("jTextField11");

        fixbranch1.setText("jTextField6");

        jLabel37.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jLabel37.setText("กำหนดเฉพาะสาขา");

        fixbranch3.setText("jTextField16");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fixbranch2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fixbranch1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fixbranch3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(fixbranch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fixbranch2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fixbranch3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plucode, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel9)
                            .addComponent(plucode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu4.setText("ฟังก์ชัน (Function)"); // NOI18N
        jMenu4.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        menu_Add1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menu_Add1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Add1.setText("เพิ่มข้อมูลใหม่ (Add New)"); // NOI18N
        menu_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_AddActionPerformed(evt);
            }
        });
        jMenu4.add(menu_Add1);

        menu_Cancle1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menu_Cancle1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Cancle1.setText("ยกเลิกการแก้ไข (Cancle All)"); // NOI18N
        menu_Cancle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CancleActionPerformed(evt);
            }
        });
        jMenu4.add(menu_Cancle1);

        menu_Save1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_Save1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Save1.setText("บันทึกข้อมูล (Save/Update)"); // NOI18N
        menu_Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_SaveActionPerformed(evt);
            }
        });
        jMenu4.add(menu_Save1);

        menu_Remove2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menu_Remove2.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_Remove2.setText("ลบข้อมูล (Remove)"); // NOI18N
        menu_Remove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Remove2ActionPerformed(evt);
            }
        });
        jMenu4.add(menu_Remove2);

        menu_exit1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menu_exit1.setFont(new java.awt.Font("Norasi", 0, 14)); // NOI18N
        menu_exit1.setText("ออกจากการทำงาน (Exit)"); // NOI18N
        menu_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exitActionPerformed(evt);
            }
        });
        jMenu4.add(menu_exit1);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1035, 811));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void btn_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancleActionPerformed
// TODO add your handling code here:
    clearForm();
}//GEN-LAST:event_btn_cancleActionPerformed

private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_btn_exitActionPerformed

private void btn_addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addNewActionPerformed
// TODO add your handling code here:
    clearForm();
}//GEN-LAST:event_btn_addNewActionPerformed

private void menu_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_AddActionPerformed
// TODO add your handling code here:
    clearForm();
}//GEN-LAST:event_menu_AddActionPerformed

private void menu_CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CancleActionPerformed
// TODO add your handling code here:
    clearForm();
}//GEN-LAST:event_menu_CancleActionPerformed

private void menu_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_SaveActionPerformed
    btn_saveActionPerformed(evt);
}//GEN-LAST:event_menu_SaveActionPerformed

private void menu_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_RemoveActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_menu_RemoveActionPerformed

private void menu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exitActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_menu_exitActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    code.requestFocus();
}//GEN-LAST:event_formWindowOpened

private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
// TODO add your handling code here:
    //int confirm = JOptionPane.showConfirmDialog(this,"คุณต้องการออกจากโปรแกรมหรือไม่","MyCps",JOptionPane.QUESTION_MESSAGE);
    //if(confirm == JOptionPane.OK_OPTION){
    dispose();
//}
}//GEN-LAST:event_btn_exitMouseClicked

private void menu_Remove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Remove1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_menu_Remove1ActionPerformed

private void btn_DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DateMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_btn_DateMouseClicked

private void btn_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DateActionPerformed

    String coCode = code.getText().trim();
    if (coCode.length() > 0 && !code.isEditable()) {
        String day = "";
        if (c1.isSelected()) {
            day += ",Sun";
        }
        if (c2.isSelected()) {
            day += ",Mon";
        }
        if (c3.isSelected()) {
            day += ",Tue";
        }
        if (c4.isSelected()) {
            day += ",Wed";
        }
        if (c5.isSelected()) {
            day += ",Thu";
        }
        if (c6.isSelected()) {
            day += ",Fri";
        }
        if (c7.isSelected()) {
            day += ",Sat";
        }
        strDay.setText(day);
    } else {
        code.requestFocus();
    }

}//GEN-LAST:event_btn_DateActionPerformed

private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_c1ActionPerformed

private void tblCuponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCuponMouseClicked
    if (evt.getClickCount() == 2) {
        actionTblcupon();
        code.setBackground(new java.awt.Color(250, 217, 184));
        code.setEditable(false);
    }
}//GEN-LAST:event_tblCuponMouseClicked

private void btn_Date1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Date1MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_btn_Date1MouseClicked

private void btn_Date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Date1ActionPerformed
    String coCode = code.getText().trim();
    if (coCode.length() > 0 && !code.isEditable()) {
        Point point = btn_Date1.getLocation();
        point.setLocation(point.getX(), point.getY());
        DateChooseDialog dcd = new DateChooseDialog(new Frame(), true, point);
        dcd.setVisible(true);
        // dcd.showDialog(new LookAndFeelFrame(), true, point);
        if (dcd.getSelectDate() != null) {
            start.setText(dateFmtT.format(dcd.getSelectDate().getTime()));
        }
        start.selectAll();
        start.requestFocus();
    } else {
        code.requestFocus();
    }


}//GEN-LAST:event_btn_Date1ActionPerformed

private void btn_Date2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Date2MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_btn_Date2MouseClicked

private void btn_Date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Date2ActionPerformed
    String coCode = code.getText().trim();
    if (coCode.length() > 0 && !code.isEditable()) {
        Point point = btn_Date2.getLocation();
        point.setLocation(point.getX(), point.getY());
        DateChooseDialog dcd = new DateChooseDialog(new Frame(), true, point);
        dcd.setVisible(true);
        // dcd.showDialog(new LookAndFeelFrame(), true, point);
        if (dcd.getSelectDate() != null) {
            end.setText(dateFmtT.format(dcd.getSelectDate().getTime()));
        }
        
    } else {
        code.requestFocus();
    }
}//GEN-LAST:event_btn_Date2ActionPerformed

private void tblCuponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCuponKeyPressed
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        actionTblcupon();
    }
}//GEN-LAST:event_tblCuponKeyPressed

private void plucodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plucodeKeyReleased
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        String plu = plucode.getText().trim();
        int tblPluSize = model2.getRowCount();
        boolean isFound = false;
        if (plu.length() > 0) {
            for (int i = 0; i < tblPluSize; i++) {
                String search = (String) model2.getValueAt(i, 0);
                if (plu.equals(search)) {
                    int confirm = JOptionPane.showConfirmDialog(this, "PLU Code นี้มีการกำหนดไว้แล้ว ต้องการยกเลิกหรือไม่", "confirm", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.YES_OPTION) {
                        Cupon_Controller cupon = new Cupon_Controller();
                        cupon.removePluCuponList(plu);
                        model2.removeRow(i);
                        plucode.setText("");
                        isFound = true;
                        break;
                    }
                }
            }
            if (!isFound) {
                Cupon_Controller cupon = new Cupon_Controller();
                String[] product = cupon.addProductToCopon(plu);
                if (product != null) {
                    cupon.insertCuponList(code.getText(), plu);
                    loadDataToTblPLU();
                    plucode.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "ไม่พบรายการสินค้านี้");
                    plucode.setText("");
                }
            }
        }
    }
}//GEN-LAST:event_plucodeKeyReleased

private void codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyReleased
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        boolean isFound = false;
        if (code.getText().trim().length() > 0 && code.getText().trim().length() < 4) {
            code.setBackground(new java.awt.Color(250, 217, 184));
            code.setEditable(false);
            startForm(true);
            name.requestFocus();
            int sizeListCupon = listCupon.size();
            for (int j = 0; j < sizeListCupon; j++) {
                String[] data = (String[]) listCupon.get(j);
                if (code.getText().trim().equals(data[0])) {
                    loadDataToTblCuponOnClick(j);
                    checkRemove = true;
                    isFound = true;
                    break;
                }
            }
            if (!isFound) {//ไม่มีใน cupon ต้องsearch ใน cuponlist

                loadDataToTblPLU();
            }

        } else {
            JOptionPane.showMessageDialog(this, "รหัสคูปอง (Cupon Code) เกินกำหนด กรุณาระบุรหัสคูปองไม่เกิน 3 ตัว");
            code.requestFocus();
            code.setText("");
        }
    }

}//GEN-LAST:event_codeKeyReleased

private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

    if (validateForm()) {
        Cupon_Controller cupon = new Cupon_Controller();
        String member = chMember.getSelectedItem().toString();
        String cuType = "";
        if (rd1.isSelected()) {
            cuType = "A";
        } else {
            cuType = "B";
        }
        CuponBean bean = new CuponBean();
        bean.setCucode(code.getText());
        bean.setCuName(name.getText());
        String ReduleDiscount ;
        if (rdDiscount.isSelected()) {
            ReduleDiscount = "Y" ;
        } else {
            ReduleDiscount = "N" ;
        }
        bean.setReduleDiscount(ReduleDiscount) ;
        String ReduleService ;
        if (rdService.isSelected()) {
            ReduleService = "Y" ;
        } else {
            ReduleService = "N" ;
        }
        bean.setReduleService(ReduleService) ;

        bean.setCuBegin(start.getText());
        bean.setCuEnd(end.getText());
        bean.setCuStrDay(strDay.getText());
        bean.setBarcode(barcode.getText());
        bean.setstrtype(strtype.getText());
        try {
            Float f = Float.parseFloat(cuDisc.getText());
            Float b = Float.parseFloat(cuDiscBath.getText());
            Float c = Float.parseFloat(salemin.getText());
            bean.setCuDisc(f);
            bean.setCuDiscBath(b);
            bean.setsalemin(c);
        } catch (Exception e) {
            bean.setCuDisc(0.00f);
            bean.setCuDiscBath(0.00f);
            bean.setsalemin(0.00f);
        }

        bean.setChkMember(member);
        bean.setCuType(cuType);
        bean.setfixbranch(fixbranch1.getText().trim()+fixbranch2.getText().trim()+fixbranch3.getText().trim());

        int plusize = model2.getRowCount();
        if (cupon.insertCupon(bean, plusize)) {
            int sizeT1 = model.getRowCount();
            for (int i = 0; i < sizeT1; i++) {
                model.removeRow(0);
            }
            clearForm();
            loadDataToTblCupon();
            JOptionPane.showMessageDialog(this, "บันทึกข้อมูลคูปองแล้ว");
        } else {
            JOptionPane.showMessageDialog(this, "เกิดความผิดพลาด ! ไม่สามารถบันทึกข้อมูลได้");
        }
    }
}//GEN-LAST:event_btn_saveActionPerformed

private void nameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseReleased
// TODO add your handling code here:
   /* if (code.getText().trim().length() > 0) {
        if (code.getText().trim().length() < 4) {
            code.setBackground(new java.awt.Color(250, 217, 184));
            code.setEditable(false);
            startForm(true);
            name.requestFocus();
            int sizeListCupon = listCupon.size();
            for (int j = 0; j < sizeListCupon; j++) {
                String[] data = (String[]) listCupon.get(j);
                if (code.getText().trim().equals(data[0])) {
                    loadDataToTblCuponOnClick(j);
                    checkRemove = true;
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "รหัสคูปอง (Cupon Code) เกินกำหนด กรุณาระบุรหัสคูปองไม่เกิน 3 ตัว");
            code.requestFocus();
            code.setText("");
        }

    } else {
        code.requestFocus();

    }*/
}//GEN-LAST:event_nameMouseReleased

private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
    String cuCode = code.getText().trim();
    if (checkRemove) {
        Cupon_Controller cupon = new Cupon_Controller();
        int confirm = JOptionPane.showConfirmDialog(this, "คุณต้องการลบข้อมูลรายการนี้หรือไม่", "confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (cupon.removeCupon(cuCode)) {
                clearForm();
                loadDataToTblCupon();
                JOptionPane.showMessageDialog(this, "ลบข้อมูลคูปองแล้ว");
            } else {
                JOptionPane.showMessageDialog(this, "เกิดความผิดพลาด ไม่สามารถลบข้อมูลคูปองได้");
            }
        }
    } else {
        code.requestFocus();
    }
}//GEN-LAST:event_btn_removeActionPerformed

private void cuDiscMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuDiscMouseReleased
    cuDisc.selectAll();
}//GEN-LAST:event_cuDiscMouseReleased

private void cuDiscBathMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuDiscBathMouseReleased
    cuDiscBath.selectAll();
}//GEN-LAST:event_cuDiscBathMouseReleased

private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
}//GEN-LAST:event_jMenu4ActionPerformed

private void menu_Remove2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Remove2ActionPerformed
    btn_removeActionPerformed(evt);
}//GEN-LAST:event_menu_Remove2ActionPerformed

private void startMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseReleased
    start.selectAll();
}//GEN-LAST:event_startMouseReleased

private void endMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endMouseReleased
    end.selectAll();
}//GEN-LAST:event_endMouseReleased

private void startKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startKeyReleased
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {        
        if (!start.getValue().equals("") || !start.getValue().equals(null)) {
            end.requestFocus();
        }
    }
}//GEN-LAST:event_startKeyReleased

private void barcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcodeKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_barcodeKeyReleased

private void btn_SaleType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaleType1ActionPerformed
    String proType = "";
    if (te1.isSelected()) {
        proType += ",E";
    }
    if (tt1.isSelected()) {
        proType += ",T";
    }
    if (td1.isSelected()) {
        proType += ",D";
    }
    if (tp1.isSelected()) {
        proType += ",P";
    }
    if (tw1.isSelected()) {
        proType += ",W";
    }
    strtype.setText(proType);
}//GEN-LAST:event_btn_SaleType1ActionPerformed

private void te1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_te1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_te1ActionPerformed

private void tt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tt1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_tt1ActionPerformed

private void tw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tw1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_tw1ActionPerformed

private void tp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_tp1ActionPerformed

private void td1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_td1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_td1ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jdi_Special_Cupon_Setup dialog = new jdi_Special_Cupon_Setup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcode;
    private javax.swing.JButton btn_Date;
    private javax.swing.JButton btn_Date1;
    private javax.swing.JButton btn_Date2;
    private javax.swing.JButton btn_SaleType1;
    private javax.swing.JButton btn_addNew;
    private javax.swing.JButton btn_cancle;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JComboBox chMember;
    private javax.swing.JTextField code;
    private javax.swing.JFormattedTextField cuDisc;
    private javax.swing.JFormattedTextField cuDiscBath;
    private javax.swing.ButtonGroup cupons;
    private javax.swing.JFormattedTextField end;
    private javax.swing.JTextField fixbranch1;
    private javax.swing.JTextField fixbranch2;
    private javax.swing.JTextField fixbranch3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JMenuItem menu_Add1;
    private javax.swing.JMenuItem menu_Cancle1;
    private javax.swing.JMenuItem menu_Remove2;
    private javax.swing.JMenuItem menu_Save1;
    private javax.swing.JMenuItem menu_exit1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField plucode;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JRadioButton rdDiscount;
    private javax.swing.JRadioButton rdService;
    private javax.swing.JRadioButton rdnDiscount;
    private javax.swing.JRadioButton rdnService;
    private javax.swing.JFormattedTextField salemin;
    private javax.swing.JFormattedTextField start;
    private javax.swing.JTextField strDay;
    private javax.swing.JTextField strtype;
    private javax.swing.JTable tblCupon;
    private javax.swing.JTable tblPLU;
    private javax.swing.JCheckBox td1;
    private javax.swing.JCheckBox te1;
    private javax.swing.JCheckBox tp1;
    private javax.swing.JCheckBox tt1;
    private javax.swing.JCheckBox tw1;
    // End of variables declaration//GEN-END:variables

    private void loadDataToTblCupon() {
        Cupon_Controller cupon = new Cupon_Controller();
        listCupon = cupon.getCuponDetail();
        int cnt = listCupon.size();
        int cuponSize = model.getRowCount();
        if (cuponSize > 0) {
            for (int i = 0; i < cuponSize; i++) {
                model.removeRow(0);
            }
        }
        for (int i = 0; i < cnt; i++) {
            String[] data = (String[]) listCupon.get(i);
            Date st = new Date();
            Date en = new Date();
            try {
                st = dateFmtE.parse(data[2]);
                en = dateFmtE.parse(data[3]);
            } catch (ParseException ex) {
                Logger.getLogger(jdi_Special_Cupon_Setup.class.getName()).log(Level.SEVERE, null, ex);
            }
            String[] tbl = {data[0], data[13],data[1], dateFmtT.format(st), dateFmtT.format(en), data[4], data[5], data[6], data[7], data[8], data[9]};
            model.addRow(tbl);
        }
    }

    private void loadDataToTblPLU() {
        Cupon_Controller cupon = new Cupon_Controller();
        java.util.List list = cupon.getCuponList(code.getText());
        int cnt = list.size();
        int rowSize = model2.getRowCount();
        if (rowSize > 0) {
            for (int i = 0; i < rowSize; i++) {
                model2.removeRow(0);
            }
        }
        for (int i = 0; i < cnt; i++) {
            String[] data = (String[]) list.get(i);
            String[] tbl = {data[0], data[1]};
            model2.addRow(tbl);
        }
    }

    private void actionTblcupon() {
        startForm(true);
        int row = tblCupon.getSelectedRow();
        loadDataToTblCuponOnClick(row);
    }

    private void loadDataToTblCuponOnClick(int row) {
        String[] data = (String[]) listCupon.get(row);

        String cu_code = data[0];
        String cu_desc = data[1];
        String cu_st = data[2];
        String cu_ed = data[3];
        String cu_str = data[4];
        String sale_str = data[14];
        java.util.Date date = new java.util.Date();
        try {
            date = dateFmtE.parse(cu_st);
            cu_st = dateFmtT.format(date);

            date = dateFmtE.parse(cu_ed);
            cu_ed = dateFmtT.format(date);

        } catch (Exception e) {
            cu_st = "00/00/0000";
            cu_ed = "00/00/0000";
        }
        c1.setSelected(false);
        c2.setSelected(false);
        c3.setSelected(false);
        c4.setSelected(false);
        c5.setSelected(false);
        c6.setSelected(false);
        c7.setSelected(false);

        String[] out = cu_str.split(",");
        for (int i = 0; i < out.length; i++) {
            if (out[i].equals("Sun")) {
                c1.setSelected(true);
            }
            if (out[i].equals("Mon")) {
                c2.setSelected(true);
            }
            if (out[i].equals("Tue")) {
                c3.setSelected(true);
            }
            if (out[i].equals("Wed")) {
                c4.setSelected(true);
            }
            if (out[i].equals("Thu")) {
                c5.setSelected(true);
            }
            if (out[i].equals("Fri")) {
                c6.setSelected(true);
            }
            if (out[i].equals("Sat")) {
                c7.setSelected(true);
            }
        }
        te1.setSelected(false);
        tt1.setSelected(false);
        td1.setSelected(false);
        tp1.setSelected(false);
        tw1.setSelected(false);

        String[] out2 = sale_str.split(",");
        for (int i = 0; i < out2.length; i++) {
            if (out2[i].equals("E")) {
                te1.setSelected(true);
            }
            if (out2[i].equals("T")) {
                tt1.setSelected(true);
            }
            if (out2[i].equals("D")) {
                td1.setSelected(true);
            }
            if (out2[i].equals("P")) {
                tp1.setSelected(true);
            }
            if (out2[i].equals("W")) {
                tw1.setSelected(true);
            }
        }
        code.setText(cu_code);
        code.setEditable(false);
        name.setText(cu_desc);
        start.setText(cu_st);
        end.setText(cu_ed);
        strDay.setText(cu_str);
        cuDisc.setText(data[10]);
        Float cd = Float.parseFloat(data[10]);
        Float cdb = Float.parseFloat(data[11]);
        cuDisc.setValue(cd);
        cuDiscBath.setText(data[11]);
        barcode.setText(data[13]) ;
        strtype.setText(data[14]) ;
        salemin.setText(data[15]) ;
        cuDiscBath.setValue(cdb);
        if (data[17].equals("Y")) {
            rdDiscount.setSelected(true);
        } else {
            rdnDiscount.setSelected(true);
        }
        if (data[18].equals("Y")) {
            rdService.setSelected(true);
        } else {
            rdnService.setSelected(true);
        }
        

        if (data[12].equals("Y")) {//ChkMember

            chMember.setSelectedIndex(0);
        } else {
            chMember.setSelectedIndex(1);
        }

        if (data[5].equals("A")) {//CuType

            rd1.setSelected(true);
        } else {
            rd2.setSelected(true);
        }
         //load fixbranch
        fixbranch1.setText("");
        fixbranch2.setText("");
        fixbranch3.setText("");
        if (data[16].length() >72) {
            if (data[16].length()>156) {
                fixbranch1.setText(data[16].substring(0, 72));
                fixbranch2.setText(data[16].substring(72,156));
                fixbranch3.setText(data[16].substring(156,data[16].length()));
            } else {
                fixbranch1.setText(data[16].substring(0, 72));
                fixbranch2.setText(data[16].substring(72,data[16].length()));
            }
        } else {
            fixbranch1.setText(data[16]);
        }
        checkRemove = true;
        loadDataToTblPLU();
    }

    private void startForm(boolean enable) {
        code.setEditable(!enable);
        //  
        name.setEditable(enable);
        barcode.setEditable(enable) ;
        fixbranch1.setEditable(enable) ;
        fixbranch2.setEditable(enable) ;
        fixbranch3.setEditable(enable) ;
        start.setEditable(enable);
        end.setEditable(enable);
        strDay.setEditable(enable);
        c1.setEnabled(enable);
        c2.setEnabled(enable);
        c3.setEnabled(enable);
        c4.setEnabled(enable);
        c5.setEnabled(enable);
        c6.setEnabled(enable);
        c7.setEnabled(enable);
        te1.setEnabled(enable);
        tt1.setEnabled(enable);
        td1.setEnabled(enable);
        tp1.setEnabled(enable);
        tw1.setEnabled(enable);
        salemin.setEnabled(enable);
        barcode.setEnabled(enable) ;

        chMember.setEnabled(enable);
        plucode.setEditable(enable);
        cuDisc.setEditable(enable);
        cuDisc.setText("0.00");
        cuDisc.setValue(0);
        cuDiscBath.setEditable(enable);
        cuDiscBath.setText("0.00");
        cuDiscBath.setValue(0);
        rd1.setEnabled(enable);
        rd2.setEnabled(enable);
    }

    public void clearForm() {
        code.setText("");
        code.requestFocus();
        code.setBackground(java.awt.Color.white);
        name.setText("");
        barcode.setText("") ;
        fixbranch1.setText("") ;
        fixbranch2.setText("") ;
        fixbranch3.setText("") ;
        rdDiscount.setSelected(true) ;
        rdService.setSelected(true) ;
        start.setText("");
        end.setText("");
        strDay.setText("");
        c1.setSelected(false);
        c2.setSelected(false);
        c3.setSelected(false);
        c4.setSelected(false);
        c5.setSelected(false);
        c6.setSelected(false);
        c7.setSelected(false);
        te1.setSelected(false);
        tt1.setSelected(false);
        td1.setSelected(false);
        tp1.setSelected(false);
        tw1.setSelected(false);
        barcode.setText("") ;
        salemin.setText("0.0") ;
        strtype.setText("") ;
        chMember.setSelectedIndex(0);
        plucode.setText("");
        cuDisc.setText("");
        cuDiscBath.setText("");
        rd1.setSelected(true);

        int cnt = tblPLU.getRowCount();
        if (cnt > 0) {
            for (int i = 0; i < cnt; i++) {
                model2.removeRow(0);
            }
        }
        checkRemove = false;
        startForm(false);
    }

    private boolean validateForm()   {
     //   JOptionPane.showMessageDialog(this, end.getText() + " "+start.getText()+" "+end.getText().compareTo(start.getText()));
       Date d1 = null;
       Date d2 = null;
        try {
            d1 = dateFmtT.parse(start.getText().trim());
            d2 = dateFmtT.parse(end.getText().trim());
        } catch (ParseException ex) {
            Logger.getLogger(jdi_Special_Cupon_Setup.class.getName()).log(Level.SEVERE, null, ex);
        }      
       
        if (code.getText().trim().equals("")) {
            code.requestFocus();
            return false;
        }  if (code.getText().trim().length() > 3) {
            code.requestFocus();
            JOptionPane.showMessageDialog(this, "รหัสคูปอง (Cupon Code) เกินกำหนด กรุณาระบุรหัสคูปองไม่เกิน 3 ตัว");
            code.setText("");
            return false;
        }  if (name.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุชื่อบัตรคูปอง");
            name.requestFocus();
            return false;
        }  if (start.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุวันที่เริ่มต้น");
            start.requestFocus();
            return false;
        }  if (end.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุวันที่สิ้นสุด");
            end.requestFocus();
            return false;
        }  if (d2.compareTo(d1) < 0) {
            JOptionPane.showMessageDialog(this, "วันที่ไม่ถูกต้อง");
            end.selectAll();
            end.requestFocus();
            return false;
        }  if (strDay.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุวัน (Day)");
            strDay.requestFocus();
            return false;
        }  if (cuDisc.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุส่วนลด %");
            cuDisc.requestFocus();
            return false;
        }  if (cuDiscBath.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุส่วนลดบาท");
            cuDiscBath.requestFocus();
            return false;
        }
        if ((!barcode.getText().trim().equals("")) && (barcode.getText().length()>8)) {
            JOptionPane.showMessageDialog(this, "กำหนด Barcode ไม่ถูกต้อง...");
            barcode.requestFocus();
            return false;
        } //
            return true;
       // }
    }
}
